
# cargo-vet audits file

[[audits.camino]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
delta = "1.1.4 -> 1.1.6"
notes = "No unsafe related code changed"

[[audits.tracing-tree]]
who = "Wim Looman <vet@nemo157.com>"
criteria = "safe-to-deploy"
delta = "0.2.4 -> 0.2.4@git:a5af2122fd427f1b8bcab2c18b703dc2c2fa349a"
notes = "I wrote the diff"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-16"
end = "2024-09-12"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-05-18"
end = "2024-09-12"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-09-12"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-09-12"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-08"
end = "2024-09-12"

[[trusted.backtrace]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2023-06-29"
end = "2024-09-12"

[[trusted.bitflags]]
criteria = "safe-to-deploy"
user-id = 3204 # Ashley Mannix (KodrAus)
start = "2019-05-02"
end = "2024-09-12"

[[trusted.byteorder]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-06-09"
end = "2024-09-12"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-01"
end = "2024-09-12"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 55123 # rust-lang-owner
start = "2022-10-29"
end = "2024-09-12"

[[trusted.cfg-if]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2024-09-12"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-09-12"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-03-28"
end = "2024-09-12"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-12-08"
end = "2024-09-12"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-04-15"
end = "2024-09-12"

[[trusted.color-eyre]]
criteria = "safe-to-deploy"
user-id = 43601 # Jane Losare-Lusby (yaahc)
start = "2020-05-07"
end = "2024-09-12"

[[trusted.color-spantrace]]
criteria = "safe-to-deploy"
user-id = 43601 # Jane Losare-Lusby (yaahc)
start = "2020-05-06"
end = "2024-09-12"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-04-13"
end = "2024-09-12"

[[trusted.culpa]]
criteria = "safe-to-deploy"
user-id = 782 # Nemo157 (Nemo157)
start = "2023-06-29"
end = "2024-09-12"

[[trusted.culpa-macros]]
criteria = "safe-to-deploy"
user-id = 782 # Nemo157 (Nemo157)
start = "2023-06-29"
end = "2024-09-12"

[[trusted.equivalent]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2023-02-05"
end = "2024-09-12"

[[trusted.eyre]]
criteria = "safe-to-deploy"
user-id = 43601 # Jane Losare-Lusby (yaahc)
start = "2020-02-05"
end = "2024-09-12"

[[trusted.flate2]]
criteria = "safe-to-deploy"
user-id = 4333 # Josh Triplett (joshtriplett)
start = "2020-09-30"
end = "2024-09-12"

[[trusted.getrandom]]
criteria = "safe-to-deploy"
user-id = 5059 # Artyom Pavlov (newpavlov)
start = "2019-06-28"
end = "2024-09-12"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2024-09-12"

[[trusted.indenter]]
criteria = "safe-to-deploy"
user-id = 43601 # Jane Losare-Lusby (yaahc)
start = "2020-02-27"
end = "2024-09-12"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539 # Josh Stone (cuviper)
start = "2020-01-15"
end = "2024-09-12"

[[trusted.is-terminal]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2022-01-22"
end = "2024-09-12"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 4333 # Josh Triplett (joshtriplett)
start = "2020-10-01"
end = "2024-09-12"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2021-01-27"
end = "2024-09-12"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-03-29"
end = "2024-09-12"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2024-09-12"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2024-09-12"

[[trusted.once_cell]]
criteria = "safe-to-deploy"
user-id = 2699 # Alex Kladov (matklad)
start = "2019-05-07"
end = "2024-09-12"

[[trusted.pin-project-lite]]
criteria = "safe-to-deploy"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2019-10-22"
end = "2024-09-12"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2024-09-12"

[[trusted.quote]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2024-09-12"

[[trusted.rand]]
criteria = "safe-to-deploy"
user-id = 1234 # Diggory Hardy (dhardy)
start = "2019-06-06"
end = "2024-09-12"

[[trusted.rustc-demangle]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2019-04-12"
end = "2024-09-12"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825 # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2024-09-12"

[[trusted.serde]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-09-12"

[[trusted.serde_bytes]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-25"
end = "2024-09-12"

[[trusted.serde_derive]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-09-12"

[[trusted.serde_spanned]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2024-09-12"

[[trusted.sharded-slab]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-10-02"
end = "2024-09-12"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2024-09-12"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2024-09-12"

[[trusted.thread_local]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-09-07"
end = "2024-09-12"

[[trusted.toml]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2024-09-12"

[[trusted.toml_datetime]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2022-10-21"
end = "2024-09-12"

[[trusted.toml_edit]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2024-09-12"

[[trusted.tracing]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-28"
end = "2024-09-12"

[[trusted.tracing-attributes]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-08-08"
end = "2024-09-12"

[[trusted.tracing-core]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-20"
end = "2024-09-12"

[[trusted.tracing-error]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2020-02-05"
end = "2024-09-12"

[[trusted.tracing-log]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-27"
end = "2024-09-12"

[[trusted.tracing-subscriber]]
criteria = "safe-to-deploy"
user-id = 1249 # Eliza Weisman (hawkw)
start = "2019-06-27"
end = "2024-09-12"

[[trusted.tracing-tree]]
criteria = "safe-to-deploy"
user-id = 1471 # Oli Scherer (oli-obk)
start = "2023-04-20"
end = "2024-09-12"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2024-09-12"

[[trusted.uuid]]
criteria = "safe-to-deploy"
user-id = 3204 # Ashley Mannix (KodrAus)
start = "2019-10-18"
end = "2024-09-12"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10 # Carl Lerche (carllerche)
start = "2022-01-03"
end = "2024-09-12"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1 # Alex Crichton (alexcrichton)
start = "2020-06-03"
end = "2024-09-12"

[[trusted.winapi]]
criteria = "safe-to-deploy"
user-id = 63 # Peter Atashian (retep998)
start = "2019-04-03"
end = "2024-09-12"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2024-09-12"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2024-09-12"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-09-12"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2024-09-12"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-09-12"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-09-12"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2024-09-12"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2024-09-12"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2024-09-12"

[[trusted.winnow]]
criteria = "safe-to-deploy"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2024-09-12"
