
# cargo-vet config file

[cargo-vet]
version = "0.8"

[imports.first-party]
url = "https://raw.githubusercontent.com/Nullus157/.github/main/supply-chain/first-party-audits.toml"

[imports.third-party]
url = "https://raw.githubusercontent.com/Nullus157/.github/main/supply-chain/third-party-audits.toml"

[policy.tracing-tree]
audit-as-crates-io = true

[[exemptions.addr2line]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.21.5"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.31"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-deploy"

[[exemptions.fastnbt]]
version = "2.4.4"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.27.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.58"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.indoc]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.65"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.owo-colors]]
version = "3.5.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.108"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.26"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.88"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.50.0"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-deploy"
